# Generated by Django 4.2.7 on 2023-11-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('artist', models.CharField(max_length=64)),
                ('album_art_path', models.CharField(max_length=128)),
                ('song_path', models.CharField(max_length=128)),
            ],
        ),
    ]
